name: Build and Test Rust Project

on:
    workflow_dispatch:
        inputs:
            project-path:
                description: "Path to Rust project"
                required: true
                default: "."
                type: string
    workflow_call:
        inputs:
            project-path:
                description: "Path to Rust project"
                required: true
                default: "."
                type: string

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings, including Clippy lints

jobs:
    build-and-test:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: ${{ inputs.project-path }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                BUILD_TARGET: [release]
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: recursive

            - name: Cache cargo registry
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ runner.os == 'Windows' && '%USERPROFILE%\.cargo\registry' || '~/.cargo/registry' }}
                      ${{ runner.os == 'Windows' && '%USERPROFILE%\.cargo\git' || '~/.cargo/git' }}
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: "10.x"

            - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
              run: cargo build --profile ${{ matrix.BUILD_TARGET }} --verbose

            - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
              run: cargo test --profile ${{ matrix.BUILD_TARGET }} --verbose

    code_check:
        runs-on: "ubuntu-latest"
        defaults:
            run:
                working-directory: ${{ inputs.project-path }}
        steps:
            - uses: actions/checkout@v5

            - name: Show Rust toolchain
              run: |
                  rustup show active-toolchain

            - name: Run Clippy
              run: cargo clippy --all-targets --all-features

            - name: Run Rustfmt
              run: cargo fmt -- --check