name: Build and Test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build_and_test:
        uses: ./.github/workflows/build-and-test.yaml
        with:
            project-path: "."